### PR TITLE
[WIP] added recursive methods into kv

### PR DESCRIPTION
**Pull request by onnimonni**
These make it easier to dump / import everything into Consul KV eg. from yaml files.

### CODE REVIEW

**Comment by johnhamelink** [comment]
Hey there,

First off, thanks for contributing, it's really appreciated :smiley: 

I've added some notes on how you can improve your contribution. In summary:

 * Can you add some rspec tests for the methods you've added?
 * Can you move the Monkey patches you've applied to `Hash` and `Array` to a separate file?
 * Can you provide a usecase for the `nested_hash_to_key_value_hash` method?

Thanks very much!

JH

**Comment by johnhamelink** [comment]
@onnimonni Are you planning on submitting this code? You've made a lot of changes but I don't want to merge this because it's a such a large PR - can you split it up into smaller chunks so we can merge into master?

**Comment by onnimonni** [comment]
I will look at it later :), this might not be as suitable for others as I thought originally.

**Comment by johnhamelink** [comment]
Thanks @onnimonni :)

**Pull request closed without merging**
