### PR TITLE
Add support for acls

### PR DESCRIPTION
**Pull request by kamaradclimber**
This patch adds support for consul acl. It allows to create/update/destroy/list and get info on acls.

It also factorize the common options used.

### CODE REVIEW

**Comment by PeterFCaswell** [comment]
Thanks! I'll be able to review this tomorrow morning EST if @johnhamelink doesn't get to it first. In the meantime, could you bump the version to 0.4.x+1, please?

**Comment by kamaradclimber** [comment]
done, I've bumped the minor revision number to reflect the api increase. Tell me if that suits you.

**Comment by PeterFCaswell** [comment]
Thank you @kamaradclimber!

**Comment by PeterFCaswell** [comment]
I very much appreciate this particular addition since I need to venture into ACLs in a couple of weeks. Thank you again @kamaradclimber

**Comment by johnhamelink** [comment]
Time for a new release I think! Thanks @kamaradclimber :+1:

**Pull request merged**
