### PR TITLE
Add prepared queries API methods

### PR DESCRIPTION
**Pull request by taharah**

### CODE REVIEW

**Comment by taharah** [comment]
I did not update the CHANGELOG since that would cause merge conflicts with the other PR I have raised. I will create a separate PR to update that when my other PR has been merged.

**Comment by evan2645** [comment]
@taharah any luck on reaching @johnhamelink or others? Happy to help maintain if necessary. Using this lib in production, need to get some of these changes in. If not, let's fork or something.

**Comment by taharah** [comment]
I'm going to try reaching out via email today. I was hoping to get some movement after the new year, but I've heard nothing as of yet. I'm using this in production as well and I would like to get it feature complete with the latest changes from v0.7.2.

**Comment by evan2645** [comment]
cool, thanks a bunch @taharah! we have taken to monkey patching our way around #118 until we can get it merged in. we'll keep an eye out for updates, do let us know what you find. thanks again

**Pull request merged**
