### PR TITLE
Converting data to a ruby hash

### PR DESCRIPTION
**Pull request by kendrickm**
This functionality converts the (potentially) nested data in consul to a nested ruby hash.

### CODE REVIEW

**Comment by johnhamelink** [comment]
@kendrickm Thanks for this PR. I'm a bit worried about the `to_hash.rb` helper - this would add a `deep_hash` function to all hashes inside *and* outside Diplomat, right? Can we not localise this to inside Diplomat so we don't potentially create an unnecessary conflict with the outside world?

**Comment by kendrickm** [comment]
@johnhamelink That makes sense. I moved it inside the class. If down the line other parts of the gem want to use it, we may think about implementing https://github.com/intridea/hashie or something for more hash support.

**Comment by kendrickm** [comment]
@johnhamelink Any chance for this to get merged soon? I utilize the consul k/v system pretty and would love to start using this

**Comment by johnhamelink** [comment]
Merged. Thank you! :smile:

**Pull request merged**
