### PR TITLE
ACL support

### PR DESCRIPTION
**Pull request by InformatiQ**
list/info/create/update/destroy and ACL from consul server

### CODE REVIEW

**Comment by johnhamelink** [comment]
Hey @InformatiQ, thanks for submitting this PR, it is very much appreciated! Could you add some specs to this PR so we can merge it?

Many thanks! :rocket:

**Comment by PeterFCaswell** [comment]
Does anyone have time to write the specs for this? (I'm pressed by hard deadlines right now.) It would be great to get Acl into the release.

**Comment by kamaradclimber** [comment]
I'll write specs for it

**Comment by johnhamelink** [comment]
Thank you @kamaradclimber

**Comment by kamaradclimber** [comment]
I don't have access to the repo of @InformatiQ so I've put the tests + his patch (with modifications) on #62

**Comment by johnhamelink** [comment]
Merged in #62. Thanks everyone.

**Pull request closed without merging**
