### PR TITLE
update faraday dependency

### PR DESCRIPTION
**Pull request by PlugIN73**

### CODE REVIEW

**Comment by pierresouchay** [comment]
@PlugIN73 Hello, Can you provide a bit more of context?
Why do you limit the version, is there is a regression?

**Comment by PlugIN73** [comment]
Hi! I've limited faraday version because 0.9 version is most popular version and there is no 0.16 version. Diplomat working at any of this version, but I don't know will it work on 1.0.0 from future release.
Version 0.9 is locked on many gems and bundler can't install some gems in which faraday have versions > 0.9
[https://github.com/lostisland/faraday/releases](https://github.com/lostisland/faraday/releases)

**Comment by pierresouchay** [comment]
Then, I propose to put a >= 0.9 and < 1.0 (with a comment saying it has not been tested on 1.0
Or to remove constraint on 1.0

**Comment by PlugIN73** [comment]
@pierresouchay fixed

**Pull request merged**
