### PR TITLE
Allow use of filters on every Health methods

### PR DESCRIPTION
**Pull request by damfle**
The informations provided by the endpoints are different enough to make it worthwhile.

### CODE REVIEW

**Comment by damfle** [comment]
Hello. Can you do the review please ? :)

**Comment by pierresouchay** [comment]
@damfle Thanks a lot for your contrubution!

**Comment by pierresouchay** [comment]
@damfle published in a new release [2.6.3](https://rubygems.org/gems/diplomat/versions/2.6.3)

**Comment by damfle** [comment]
Thanks ! :)

**Pull request merged**
