### PR TITLE
Add recursion option so we can grab keys recursively

### PR DESCRIPTION
**Pull request by beso323**
This let's us do something like 

``foo = Diplomat::Kv.get('/test', {:recurse => true})``

Which will return all values under /test

### CODE REVIEW

**Comment by johnhamelink** [comment]
Hey @beso323, thanks for the PR! Can you revise the version number change - the version should be 0.10.2 because it's a minor change, not a patch (this gem follows [semver][(http://semver.org))

**Comment by beso323** [comment]
Done!

**Comment by johnhamelink** [comment]
Thanks, merged! :+1:

**Comment by johnhamelink** [comment]
Released in [v0.10.2](https://rubygems.org/gems/diplomat/versions/0.10.2)

**Pull request merged**
