### PR TITLE
Resolve inconsistent recursive return for Diplomat::KV.get when singl…

### LINKED ISSUE #119: Kv.get /w recurse: true is not consistent
`Kv.get` with recurse: true is not consistent if there is only single key were returned.

I am expecting array of key/values, but if there is only single key it would return just its value.

```ruby
Diplomat::Kv.put('hello/world', 'test')

Diplomat::Kv.get('hello', recurse: true)
# current:
# => 'test'
# expected
# => [{ key: 'hello/world', value: 'test'}]
```

Current workaround is specifying `decode_values: true`:
```ruby
Diplomat::Kv.get('hello', recurse: true, decode_values: true)
# => {[ 'Key' => 'hello/world', 'Value' => 'test', ... }]

```

But there is no way to make ``convert_to_hash`` to work with single key atm.

### PR DESCRIPTION
**Pull request by taharah**
…e value return

Resolves #119

### CODE REVIEW

**Comment by t3hk0d3** [comment]
Not sure this is backward-compatible. I think it would break interface of non-recursive get.

**Comment by taharah** [comment]
Yea I was thinking the same thing since it broke the spec tests and I would do a major version bump if/when this got merged.

**Comment by EugenMayer** [comment]
This is so much needed, i would really love to see this getting fixed - major version bump is reasonable. Anything i can do to move this forward? Right now, i create dummy values in consul to avoid this bug... which is crazy

**Comment by t3hk0d3** [comment]
@EugenMayer Well, quick workaround is to parse KV data yourself.

**Comment by taharah** [comment]
@eugenmayer I just saw there was a major version bump in the past week, so I'm going to get this staged up and pushed out as 2.0.1 since I know this is really needed. In the next month or so, I plan to put some real TLC into this gem as I'll need it for an upcoming project.

**Comment by taharah** [comment]
@EugenMayer I've based the changes onto the latest master branch, so if you could give this a quick +1 I'll move forward with getting this merged and released.

**Comment by EugenMayer** [comment]
i am so happy to have this one in, totally +1

**Comment by taharah** [comment]
@EugenMayer v2.0.1 has been tagged and released. enjoy!

**Comment by EugenMayer** [comment]
well this more or less has broken all diplomat integrations and i think the reason is, it does not play nice with "convert_to_hash" .. this is a huge issue.

**Comment by EugenMayer** [comment]
created https://github.com/WeAreFarmGeek/diplomat/issues/152

**Comment by johnhamelink** [comment]
@eugenmayer could you provide more detail please? Are you comparing all diplomat integrations for the previous major revision, of do you mean the 2.0.1 release compared with 2.0.0?

**Comment by johnhamelink** [comment]
Thanks the issue answers my question

**Pull request merged**
