### PR TITLE
Add external service registration

### LINKED ISSUE #61: Feature: allow using catalog endpoint when creating services
This is required to register [external services](https://www.consul.io/docs/guides/external.html)

### PR DESCRIPTION
**Pull request by ryansch**
Fixes #61

### CODE REVIEW

**Comment by johnhamelink** [comment]
@ryansch Thanks for this commit (sorry it's taken me so long to look at it). [Travis is currently returning a failure for ruby 1.9.3](https://s3.amazonaws.com/archive.travis-ci.org/jobs/110012842/log.txt). Do you reckon you could take a look at that and fix it, so I can merge?

**Comment by ryansch** [comment]
That test failure appears to be related to bundler.  I've rebased on master which included an update to travis's config.

**Comment by ryansch** [comment]
ping @johnhamelink ^

(sorry forgot to mention you)

**Comment by johnhamelink** [comment]
Thanks @ryansch :+1:

**Pull request merged**
